// Generated by gencpp from file enph353_gazebo/SubmitPlateResponse.msg
// DO NOT EDIT!


#ifndef ENPH353_GAZEBO_MESSAGE_SUBMITPLATERESPONSE_H
#define ENPH353_GAZEBO_MESSAGE_SUBMITPLATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace enph353_gazebo
{
template <class ContainerAllocator>
struct SubmitPlateResponse_
{
  typedef SubmitPlateResponse_<ContainerAllocator> Type;

  SubmitPlateResponse_()
    : correct(false)  {
    }
  SubmitPlateResponse_(const ContainerAllocator& _alloc)
    : correct(false)  {
  (void)_alloc;
    }



   typedef uint8_t _correct_type;
  _correct_type correct;





  typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SubmitPlateResponse_

typedef ::enph353_gazebo::SubmitPlateResponse_<std::allocator<void> > SubmitPlateResponse;

typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateResponse > SubmitPlateResponsePtr;
typedef boost::shared_ptr< ::enph353_gazebo::SubmitPlateResponse const> SubmitPlateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace enph353_gazebo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d7b90c75811aaad705aac4e2b606238";
  }

  static const char* value(const ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d7b90c75811aaadULL;
  static const uint64_t static_value2 = 0x705aac4e2b606238ULL;
};

template<class ContainerAllocator>
struct DataType< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "enph353_gazebo/SubmitPlateResponse";
  }

  static const char* value(const ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool correct\n"
;
  }

  static const char* value(const ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.correct);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubmitPlateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::enph353_gazebo::SubmitPlateResponse_<ContainerAllocator>& v)
  {
    s << indent << "correct: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.correct);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENPH353_GAZEBO_MESSAGE_SUBMITPLATERESPONSE_H
